### ISSUE TITLE
API still valid?

### ISSUE THREAD

**Issue by bc3tech** [arraylabs/myq#8]
Hey folks,

I know this repo's been dormant for a while but nonetheless it looks like y'all put a lot of work in to it. I'm trying to utilize the general flow seen here but am having no luck from the endpoints I see in the code. I keep getting back an HTTP 200 but w/ content:

```html
<html>
    <head>
        <title>Request Rejected</title>
    </head>
    <body>Your request has been denied.
        <br>
        <br>[13495076365845689385]
    </body>
</html>
```

Anything I can do to help?

**Comment by brbeaird** [comment]
Try changing the Liftmaster AppID (line 31) to NWknvuBd7LoFHfXmKNMBcgajXtZEgKUh4V7WNzMidrpUUluDpVYVZx+xT4PCM5Kx

**Comment by bc3tech** [comment]
working values can be found here: https://github.com/bc3tech/Alexa-MyQGarage/blob/f6d9b50acb6c578792d7f57311b1a29878c07170/dotnet/AzureFunction/MyQFunctionApp/sample.local.settings.json#L6
